const dummyData = [
	{
		employer_name: "StairwaySoft, Ltd.",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "BeBee",
		job_id: "tBgaiciwgc_lyw4tAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React Developer",
		job_apply_link:
			"https://ae.bebee.com/job/20240115-2fba60c6473cd810d622e336f2a7ac79",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.4995,
		apply_options: [
			{
				publisher: "BeBee",
				apply_link:
					"https://ae.bebee.com/job/20240115-2fba60c6473cd810d622e336f2a7ac79",
				is_direct: false,
			},
			{
				publisher: "Jobs Trabajo.org",
				apply_link:
					"https://ae.trabajo.org/job-721-20240115-c07c22a9a0584024961bfbe5619f8546",
				is_direct: false,
			},
			{
				publisher: "Jobilize",
				apply_link:
					"https://www.jobilize.com/job/ae-united-arab-emirates-react-developer-stairwaysoft-ltd-hiring-now",
				is_direct: false,
			},
		],
		job_description:
			"React Developer We're expanding our team of software engineers. This opportunity will be a great fit for middle front-end developers with good React knowledge and experience.\n\nAdvanced financial systems that allow the organization and employees to contribute easily, save time and paperwork and improve corporate responsibility benchmarks.\nOh, and everything is online, of course.\n\nWhat you will need:\n2+ years of experience with (both class and functional components)\n\nEnglish communication skills (spoken and written)\n\nProven leadership abilities and willingness to share knowledge with juniorsStrong problem-solving, troubleshooting, and interpersonal skillsProficient knowledge of Redux, React Context, React HooksExperience developing responsive web applicationGetting data from REST and GraphQL APIsStrong computer science fundamentals:\n\ndata structures, algorithms\n\nWhat would be great:\nKnowledgeable experience with testing React applications\n• Jest or Cypress.\nio\n\nBuilding applications with WebpackExperience with Twitter Bootstrap and other component frameworksExperience with Location:\n\nAny location Type of employment:\n\nRemote Specialization:\n\nFront-end send resume 10+ years on marketplace 40+ project implemented 50+ professional specialists StairwaySoft is a global engineering provider of innovative software development services with a team of expert engineers.\nWe service various businesses internationally to create solutionsand help companies achieve their technology goals.\nWe build software solutions through an ever-expandingUNIQUE HYBRID of Eastern European, Middle Eastand Central Asia Engineering matched with Israeli Innovation (up to 10Mb combined size, only .docx, .pdf file)\n#J-18808-Ljbffr",
		job_is_remote: false,
		job_posted_at_timestamp: 1705294153,
		job_posted_at_datetime_utc: "2024-01-15T04:49:13.000Z",
		job_city: null,
		job_state: null,
		job_country: "AE",
		job_latitude: 23.424076,
		job_longitude: 53.847816,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=tBgaiciwgc_lyw4tAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-01-23T00:00:00.000Z",
		job_offer_expiration_timestamp: 1705968000,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 24,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "Techcarrot",
		employer_logo:
			"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUM8xfloHsrGHZPfpIv1-1rOnAHm3au-tqSidt&s=0",
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Edarabia",
		job_id: "ghhPxjAtBYRSPb7UAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Frontend Developer (React)",
		job_apply_link:
			"https://www.edarabia.com/frontend-developer-react-techcarrot-dubai-uae/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.6428,
		apply_options: [
			{
				publisher: "Edarabia",
				apply_link:
					"https://www.edarabia.com/frontend-developer-react-techcarrot-dubai-uae/",
				is_direct: false,
			},
			{
				publisher: "Naukrigulf.com",
				apply_link:
					"https://www.naukrigulf.com/frontend-developer-jobs-in-dubai-uae-in-techcarrot-3-to-5-years-n-cd-20010167-jid-291123500951",
				is_direct: false,
			},
			{
				publisher: "Energy Jobline",
				apply_link:
					"https://www.energyjobline.com/job/frontend-developer-react-18953888",
				is_direct: false,
			},
			{
				publisher: "MNC Jobs",
				apply_link:
					"https://www.mncjobsgulf.com/jobs/frontend-developer-dubai-1414233",
				is_direct: false,
			},
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/frontend-developer-react--dubai-techcarrot-dubai--d8a79cae8b/",
				is_direct: false,
			},
			{
				publisher: "Trabajo.org",
				apply_link:
					"https://ae.trabajo.org/job-844-20231225-6563968911ffb9cc90343b45f44fffb6",
				is_direct: false,
			},
			{
				publisher: "Talent.com",
				apply_link: "https://ae.talent.com/view?id=d8a79cae8b16",
				is_direct: false,
			},
			{
				publisher: "Q4Jobs United Arab Emirates",
				apply_link: "https://ae.q4jobs.com/job/techcarrot-job-3/",
				is_direct: false,
			},
		],
		job_description:
			"Job Summary\n• Proficiency with Javascript, HTML5, CSS, Javascript, jQuery/Bootstrap and JSON.\n• Must have an excellent knowledge of React.\n• Proficient understanding of cross-browser compatibility issues.\n• Good understanding of AJAX and Javascript DOM.\n• Design and build advanced, scalable applications on azure.\n• Ability to understand business requirements and map to latest azure features.\n• A good understanding of how Azure DevOps works and maintain code repositories from the same.\n• Should be able to act as a consultant to team members on technical matters.\n• Work with the product and design teams to understand end-user requirements and use cases and translate them pragmatic and effective technical solutions.\n• Integrate with other our backend services (JSON, XML, etc.)\n• Continuously discover, evaluate, and implement new technologies to maximize development efficiency.\n• Unit-test code for robustness, including edge cases, usability, and general reliability.\n• Ability to read code done by any developer and updating that code.\n\nSkills\n• At minimum of 3 - 5 years of experience in frontend development.\n• Knowledge on consuming REST APIs.\n• 4+ years of experience in building responsive website using HTML, CSS, Javascript, jQuery/Bootstrap and JSON.\n• Proficient with Javascript framework such as Angular or React, preferably REACT experience with Redux.\n• Familiarity with server-side technologies like node.js.\n• Experience in SQL Server TSQL and Admin knowledge.\n• Implementation experience in Azure landscape.\n• Working and integration with Azure and on-premise components..\n• Good understanding of the development life cycle. Working knowledge of the general mobile landscape, architectures, trends, and emerging technologies.\n• Experience in working with third-party libraries and APIs.\n• Good contributions in Github or Azure Devops is preferred.\n• Excellent communicator (written and verbal, formal and informal).",
		job_is_remote: false,
		job_posted_at_timestamp: 1704052861,
		job_posted_at_datetime_utc: "2023-12-31T20:01:01.000Z",
		job_city: "دبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 25.20485,
		job_longitude: 55.270782,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=ghhPxjAtBYRSPb7UAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-01-28T00:00:00.000Z",
		job_offer_expiration_timestamp: 1706400000,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 36,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "Times World",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Expertini",
		job_id: "ctbf2whs1cZoq92aAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React developer",
		job_apply_link:
			"https://ae.expertini.com/jobs/job/react-developer-dubai-times-world-411-117771/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.4962,
		apply_options: [
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/react-developer-dubai-times-world-411-117771/",
				is_direct: false,
			},
			{
				publisher: "WhatJobs",
				apply_link:
					"https://en-ae.whatjobs.com/job/React-developer/dubai-dubai/20034774",
				is_direct: false,
			},
		],
		job_description:
			"Department: Software DevelopmentJob Type: PermanentLocation: DubaiKey responsibilities:Reviewing application requirements and interface designs.Identifying web-based user interactions.Developing and implementing highly responsive user interface components using react conceptsBuilding reusable components and front-end libraries for future useTroubleshooting interface software and debugging application codes.Monitoring and improving front-end performance.Documenting application changes and developing updates.Translating designs and wireframes into high quality codeAbility to execute to ReactJs directly in the Nodejs environment. Requirements (Qualifications/Experience/Competencies)Bachelor’s degree in computer science, information technology, or a similar field.Experience with REACTjs and NodejsExperience with HTML / CSSExperience with REST API'sGit knowledge is a plusGreat interpersonal and communication skillsPrevious experience working as a react.js developer.Knowledge of REACT tools including React.js, Webpack, Enzyme, Redux, and Flux.Experience with user interface design.Leading provider of data management, market research, analytics and business intelligence solutions. Pioneer in data unification and bringing cognitive solutions to practical systems.13, Floor 1, Sahya TowerGovt. Cyberpark CampusCalicut, Kerala, India 673 016Tel: +91 (495) 243 1830 Timesworld is certified for ISO 9001:2015 and ISO 27001:2013.Timesworld is registered with the ICA Data Protection Act 2018 No. ZA473769 and EU-GDPR knowledge certified by Information Security Institute & endorsed by European Risk Policy Institute. Timesworld is a corporate member of ESOMAR (European Society for Opinion and Market Research).We have updated our privacy policy as per GDPR Compliance. READ MORE HIDE\n#J-18808-Ljbffr",
		job_is_remote: false,
		job_posted_at_timestamp: 1704326400,
		job_posted_at_datetime_utc: "2024-01-04T00:00:00.000Z",
		job_city: "دبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 25.20485,
		job_longitude: 55.270782,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=ctbf2whs1cZoq92aAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-01-18T00:00:00.000Z",
		job_offer_expiration_timestamp: 1705536000,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: true,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "Techcarrot",
		employer_logo:
			"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUM8xfloHsrGHZPfpIv1-1rOnAHm3au-tqSidt&s=0",
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Edarabia",
		job_id: "CH2wuWP-jF5joBw_AAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React Developer",
		job_apply_link:
			"https://www.edarabia.com/react-developer-techcarrot-dubai-uae/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.6428,
		apply_options: [
			{
				publisher: "Edarabia",
				apply_link:
					"https://www.edarabia.com/react-developer-techcarrot-dubai-uae/",
				is_direct: false,
			},
			{
				publisher: "Naukrigulf.com",
				apply_link:
					"https://www.naukrigulf.com/react-developer-jobs-in-dubai-uae-in-techcarrot-4-to-7-years-n-cd-20010167-jid-291123501378",
				is_direct: false,
			},
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/react-developer-dubai-techcarrot-dubai--8b2316039f/",
				is_direct: false,
			},
			{
				publisher: "Jobs Trabajo.org",
				apply_link:
					"https://ae.trabajo.org/job-721-20240104-5ae0c12ba33b3d026dae9e7532a753f6",
				is_direct: false,
			},
			{
				publisher: "Jooble",
				apply_link: "https://ae.jooble.org/jdp/-6305331837498806125",
				is_direct: false,
			},
			{
				publisher: "WhatJobs",
				apply_link:
					"https://en-ae.whatjobs.com/job/React-Developer/dubai-dubai/20031970",
				is_direct: false,
			},
			{
				publisher: "Jobrapido.com",
				apply_link: "https://ae.jobrapido.com/jobpreview/64997528",
				is_direct: false,
			},
			{
				publisher: "Hiring - Hiring",
				apply_link:
					"https://hiring.com.pk/job/react-developer-jobs-in-dubai-2022-techcarrot/",
				is_direct: true,
			},
		],
		job_description:
			"Job Summary\n• Responsible for the design and implementation of user interfaces (UIs) and UI components using React.\n• Expertise in using React in different projects and a deep understanding of all stages of the software development life cycle.\n• Expertise in write, test, debug, and implement code to meet user requirements.\n• A thorough understanding of React and its core principles.\n• Familiarity with front-end build pipelines and development tools, such as Babel and Webpack.\n• Ability to understand business requirements and translate them into technical requirements.\n• Experience with React Native components.\n• Experience in working in containerized environment.\n• Working experience with integrating to single sign on with any external SSO library.",
		job_is_remote: false,
		job_posted_at_timestamp: 1704052861,
		job_posted_at_datetime_utc: "2023-12-31T20:01:01.000Z",
		job_city: "دبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 25.20485,
		job_longitude: 55.270782,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=CH2wuWP-jF5joBw_AAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-01-29T00:00:00.000Z",
		job_offer_expiration_timestamp: 1706486400,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "The Team Builders",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Expertini",
		job_id: "_G9pIM8o8FvnDUF4AAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React.JS Developer Jobs In Dubai UAE 2023 | The Team Builders",
		job_apply_link:
			"https://ae.expertini.com/jobs/job/react-js-developer-jobs-in-dubai-uae-2023-the-te-dubai-the-team-builders-411-109354/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.4872,
		apply_options: [
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/react-js-developer-jobs-in-dubai-uae-2023-the-te-dubai-the-team-builders-411-109354/",
				is_direct: false,
			},
			{
				publisher: "Jooble",
				apply_link: "https://ae.jooble.org/jdp/4132559423444438120",
				is_direct: false,
			},
			{
				publisher: "WhatJobs",
				apply_link:
					"https://en-ae.whatjobs.com/job/React-JS-Developer-Jobs/dubai-dubai/20069304",
				is_direct: false,
			},
			{
				publisher: "Jobrapido.com",
				apply_link: "https://ae.jobrapido.com/jobpreview/62578519",
				is_direct: false,
			},
			{
				publisher: "Jobilize",
				apply_link:
					"https://www.jobilize.com/job/ae-dubai-react-js-developer-uae-2023-team-builders-hiring-now-job",
				is_direct: false,
			},
		],
		job_description:
			"React.JS Developer Jobs In Dubai UAE 2023 | The Team Builders\nFor More Top Organization Jobs Click Here\nDescription:\nPlease find the job details below and if you are interested in this opportunity, please share your updated resume to m.bhawna@valuelabs.com\nResponsibilities:\n\nMinimum 5 years of coding experience in ReactJS (TypeScript), HTML, Tailwind CSS, CSS-Pre-processors or CSS-in-JS in creating Enterprise Applications with high performance for Responsive Web Applications\nDeveloping and implementing highly-responsive user interface components using React concepts. (self-contained, reusable, and testable modules and components)\nArchitecting and automating the build process for production, using task runners or scripts\nKnowledge of Data Structures for TypeScript\nMonitoring and improving front-end performance.\nBanking or Retail domains are must have.\n\nRequirements:\n\nExperience in following best Coding, Security, Unit testing and Documentation standards and practices\nExperience in Agile methodology.\nEnsure quality of technical and application architecture and design of systems across the organisation.\nEffectively research and benchmark technology against other best in class technologies.\n\n#J-18808-Ljbffr",
		job_is_remote: false,
		job_posted_at_timestamp: 1705104000,
		job_posted_at_datetime_utc: "2024-01-13T00:00:00.000Z",
		job_city: "دبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 25.20485,
		job_longitude: 55.270782,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=_G9pIM8o8FvnDUF4AAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-01-27T00:00:00.000Z",
		job_offer_expiration_timestamp: 1706313600,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 60,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "Marc Ellis Consulting",
		employer_logo:
			"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSm4Qo26D0SJJz7HPTO_Fi2r7bUx_s1KKaBZWqT&s=0",
		employer_website: "http://marc-ellis.com",
		employer_company_type: null,
		job_publisher: "Indeed",
		job_id: "PqFGY-fkraCjksRIAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Front End React JS Developer Permanent",
		job_apply_link: "https://ae.indeed.com/viewjob?jk=eb0ad995e07c36a7",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.6032,
		apply_options: [
			{
				publisher: "Indeed",
				apply_link: "https://ae.indeed.com/viewjob?jk=eb0ad995e07c36a7",
				is_direct: false,
			},
		],
		job_description:
			"BASIC INFORMATION ON THE ROLE\n\nPosition Title\nReact JS Developer\n\nReports To Technology and Engineering Head\n\nUnit / Function IT Division\n\nDepartment Grade\n\nNo. of Reportees Location\n\nJOB PURPOSE\n\nA ReactJS developer is responsible for designing and implementing UI components for JavaScript-based web\napplications and mobile applications with the use of open-source library infrastructure.\n\nKEY RESPONSIBILITIES\n\nKey Responsibilities\n• We are looking for a skilled ReactJS Developer.\n• Experience implementing applications using ReactJS\n• In this role, you will be responsible for developing and implementing use\n\nR interface Components using ES6, ReactJS concepts (Function\n\nbased), and workflows such as Redux or need to have knowledge on\n\nstate management .\n• Should have in-depth knowledge of JavaScript and React concepts.\n• Should be able to write the best optimized code as per the react and\n\nES6 standards\n• Coding skills, and a good understanding of the\n\nintegration of REST & Authentication services.\n• Hands on experience with JavaScript Development on both client and\n\nserver-side.\n• Should have a deep understanding in the virtual DOM.\n• Knowledge of the following will be considered as an advantage:\n• Consumer Web Development Experience for High-Traffic, Public Facing\n\nweb applications\n• Knowledge of NodeJS, ExpressJS added advantage.\n• Experience with writing unit test cases also a plus.\n• Experience in micro services architecture also a plus.\n• Experience with cloud technologies also a plus.\n\nEducational and Technical\nQualifications\n• A bachelor’s degree in computer science, information technology, or a\n\nrelated field.\n\nLanguage Skills\nEnglish\n\nYears & Nature of\nExperience\n\n4+ years of experience as a React JS Developer.\n\nJOB DESCRIPTION DOCUMENTATION",
		job_is_remote: false,
		job_posted_at_timestamp: 1703001216,
		job_posted_at_datetime_utc: "2023-12-19T15:53:36.000Z",
		job_city: null,
		job_state: null,
		job_country: "AE",
		job_latitude: 23.424076,
		job_longitude: 53.847816,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=PqFGY-fkraCjksRIAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-05-11T14:09:18.000Z",
		job_offer_expiration_timestamp: 1715436558,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 48,
			experience_mentioned: true,
			experience_preferred: true,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "Ombori",
		employer_logo:
			"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiKC2005Uaooop8mPiaGw2G1NEBcqEzSzWaMyz&s=0",
		employer_website: "http://ombori.com",
		employer_company_type: null,
		job_publisher: "Jobs By Workable",
		job_id: "FcGPQ-m-CIdZycN7AAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "Fullstack Developer (Node/React) - Dubai",
		job_apply_link: "https://apply.workable.com/ombori-career/j/90B2727D25/",
		job_apply_is_direct: true,
		job_apply_quality_score: 0.7415,
		apply_options: [
			{
				publisher: "Jobs By Workable",
				apply_link: "https://apply.workable.com/ombori-career/j/90B2727D25/",
				is_direct: true,
			},
			{
				publisher: "Indeed",
				apply_link: "https://ae.indeed.com/viewjob?jk=41fcb7f20be0e1fc",
				is_direct: true,
			},
			{
				publisher: "LinkedIn",
				apply_link:
					"https://ae.linkedin.com/jobs/view/fullstack-developer-node-react-dubai-at-ombori-3657613374",
				is_direct: false,
			},
			{
				publisher: "Glassdoor",
				apply_link:
					"https://www.glassdoor.co.in/job-listing/fullstack-developer-node-react-dubai-ombori-JV_IC2204498_KO0,36_KE37,43.htm?jl=1008689934472",
				is_direct: true,
			},
			{
				publisher: "Energy Jobline",
				apply_link:
					"https://www.energyjobline.com/job/fullstack-developer-node-react-dubai-17505317",
				is_direct: false,
			},
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/fullstack-developer-node-react-dubai-dubai-ombori-a3c34a14c7/",
				is_direct: false,
			},
			{
				publisher: "Sercanto",
				apply_link:
					"https://www.sercanto.ae/detail/a/fullstack-developer-node-react_dubai_75320851",
				is_direct: false,
			},
			{
				publisher: "Jooble",
				apply_link: "https://ae.jooble.org/jdp/6352649170636019792",
				is_direct: false,
			},
		],
		job_description:
			"OmboriGrid is hiring a Fullstack Developer to work in Dubai.\n\nWhat does OmboriGrid do?\n\nWe are creating the market leading Store Digitalization Platform to power the best in-store shopping experiences for customers and empower employees.\n\nWe bridge a wide range of IoT devices, AI and machine learning powered cognitive services with touch screens and mobile phones to create solutions that are memorable, easy to use, and delight our customers.\n\nWe're growing fast\nIn February 2021 we took second round of investment of 60million SEK to fund the next stage of our expansion.\n\nFind out more about us on our Website and YouTube channel.\n\nWhat will you be doing?\n\nYou will NOT be building yet another web or mobile app! We are looking for ambitious and creative software engineers that are up for a challenge. Our fullstack position consists of working with cloud-based backend, modern frontend, IoT ecosystem and a wide variety of hardware.\n\nWe are very passionate about technology. We use the latest and greatest tools and we’re always looking for new ways to innovate. Everyone in the team actively influences the design and functionality of our products.\n\nYour role will be to develop exciting IoT solutions that improve the lives of end users. This involves developing and maintaining core platform modules as well as user-facing features across our product range:\n• Developing backend services and APIs on top of Azure cloud platform using Node\n• Implementing new user-facing UI features using React\n• Working with IoT devices and other hardware components\n• Building reusable platform components, tools and libraries\n• Optimising components for maximum performance across a vast array of web-capable devices and browsers\n• Coordinating development efforts with colleagues as well as customer tech teams\n• Following DevOps principles\n\nAre you the right fit?\n\nWe’re looking for someone who has:\n• Experience in a similar role. You need hands-on experience with both backend and frontend.\n• Experience with Node, React, JavaScript and TypeScript. You will be working a lot with all.\n• Cloud exposure. Familiarity with Azure cloud platform or other cloud services will help you a lot.\n• Business to technical. Ability to understand business requirements and translate them into technical requirements. Being comfortable in technical discussions and in conversation with clients.\n• Strong communication and people skills. You will need to be fluent in both written and spoken English. You will also need to be comfortable working with colleagues and clients for whom English is not a primary language.\n• Self-starter attitude. You will enjoy this role if you like responsibility and accountability.\n\nWe work in a hybrid mode - the ability to visit our office to work with real devices and hardware, whenever needed, is important.\n\nWe’d love it if you also had the following:\n• IoT/hardware interest. It's great if you have interest in IoT solutions or prior experience with IoT technologies.\n• Product interest. Experience working in a product-oriented company will be a plus.\n\nWhy join Ombori?\n\nWe’re looking for people who relish a challenge and enjoy pushing themselves. Don’t expect to stay in your comfort zone - our clients are demanding, and they expect the best. But here’s what we offer you.\n• Be part of a growing international team of talented professionals. You’ll find yourself working alongside people from countries such as Sweden, Poland, China, Hungary, the UK, and the Philippines.\n• Work on challenging, innovative projects with high profile clients and partners throughout the world. You’ll have the satisfaction that comes from delivering ground-breaking results that will be used by millions of people together with our clients including well-known brands like Target, Dufry, IKEA, H&M, Lindt, Max Fashion, and ACE Hardware and partners like Microsoft, Samsung, Intel, ITAB, Avanade, Tech Data.\n• Develop your full potential. We pride ourselves on having a culture that allows everyone to feel valued and empowered. As part of Ombori, you’ll be expected to step up and take ownership of whatever you work on. Show us what you can do and carve out a role that’s perfect for you.\n\nInterested? Let’s talk.",
		job_is_remote: false,
		job_posted_at_timestamp: 1686009600,
		job_posted_at_datetime_utc: "2023-06-06T00:00:00.000Z",
		job_city: "دبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 25.20485,
		job_longitude: 55.270782,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=FcGPQ-m-CIdZycN7AAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: null,
		job_offer_expiration_timestamp: null,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: true,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113300",
		job_onet_job_zone: "4",
	},
	{
		employer_name: "ERNIESYS",
		employer_logo: null,
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Indeed",
		job_id: "xKsR7N-AqmsV-f3aAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React Developer",
		job_apply_link: "https://ae.indeed.com/viewjob?jk=cf0d9ec391829dd3",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.5993,
		apply_options: [
			{
				publisher: "Indeed",
				apply_link: "https://ae.indeed.com/viewjob?jk=cf0d9ec391829dd3",
				is_direct: false,
			},
			{
				publisher: "Glassdoor",
				apply_link:
					"https://www.glassdoor.fr/job-listing/react-developer-erniesys-JV_KO0,15_KE16,24.htm?jl=1007853260031",
				is_direct: false,
			},
			{
				publisher: "Jobrapido.com",
				apply_link: "https://ae.jobrapido.com/jobpreview/61890520",
				is_direct: false,
			},
		],
		job_description:
			"Number of openings | 01\n\nJob ID | 2021-1016\n\nJob Locations |UAE\n\nPosition Type | Full Time\n\nPosted Date | 27/04/2021\n\nRequirements\n• Experience designing and developing client applications for large, horizontally scalable, high-transaction volume systems.\n• Experience developing and deploying in a multi-tenant cloud environment (AWS, GDC, Azure).\n• Expert in React, Node.js, and Javascript programming languages.\n• Knowledgeable in Java and/or Go programming languages.\n• Self-driven: able to innovate, plan, and execute with autonomy.\n• Excellent verbal and written communication skills.",
		job_is_remote: false,
		job_posted_at_timestamp: 1652257585,
		job_posted_at_datetime_utc: "2022-05-11T08:26:25.000Z",
		job_city: null,
		job_state: null,
		job_country: "AE",
		job_latitude: 23.424076,
		job_longitude: 53.847816,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=xKsR7N-AqmsV-f3aAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-05-14T05:52:23.000Z",
		job_offer_expiration_timestamp: 1715665943,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: null,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "ECS ME LLC",
		employer_logo:
			"https://media.licdn.com/dms/image/C560BAQFFwGurr-_RhQ/company-logo_200_200/0/1645680034886/ecsme_llc_logo?e=2147483647&v=beta&t=CaocyAEKS6tO5wNPDM5D0xjFwnuK7lrJe9Elh3mCQYw",
		employer_website: "http://www.ecsme.ae",
		employer_company_type: null,
		job_publisher: "Expertini",
		job_id: "rB-hrC0Y8rrN7X-qAAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React.js front-end and Node.js back-end Developer",
		job_apply_link:
			"https://ae.expertini.com/jobs/job/react-js-front-end-and-node-js-back-end-developer-dubai-ecs-me-llc-1968-23195/",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.51,
		apply_options: [
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/react-js-front-end-and-node-js-back-end-developer-dubai-ecs-me-llc-1968-23195/",
				is_direct: false,
			},
			{
				publisher: "BeBee",
				apply_link:
					"https://ae.bebee.com/job/20240107-d65cab707a4d7d40ac5f6b6b076805e3",
				is_direct: false,
			},
			{
				publisher: "WhatJobs",
				apply_link:
					"https://en-ae.whatjobs.com/job/React-js-front-end-and/dubai-dubai/19992583",
				is_direct: false,
			},
			{
				publisher: "Trabajo.org",
				apply_link:
					"https://ae.trabajo.org/job-721-20231226-82b3f2e7da9349674b59ba900d53d7bd",
				is_direct: false,
			},
			{
				publisher: "Jobilize",
				apply_link:
					"https://www.jobilize.com/job/ae-dubai-react-js-front-end-node-back-developer-ecs-me-hiring-now",
				is_direct: false,
			},
		],
		job_description:
			"Technical SKILLS The key skills and experience you will bring to this role include:Strong experience React js, Node js and SQL Server\nStrong understanding of web standards (http protocols, browser, html, etc)\nExperience providing REST/SOAP APIs for user interface consumption\nWell, understanding of HTML5, CSS Material Design, Bootstrap\nExperience of building web applications using JavaScript/jQuery/AJAX\nStrong understanding of Object-Oriented Programming (OOP) concepts and enterprise design patterns\nKnowledge of serverless computing\nExperienced with the Microsoft Azure platform\nStrong Hands-on experience on MS SQL & My SQL (Complex queries, Stored procedures, Views, Functions, Triggers) must include Query Optimization.\nExposure to an Agile Development Methodology would be beneficial\nRevise, update, refactor and debug codeKEY BEHAVIOURS & PERSONAL ATTRIBUTESAble to work through complex requirements and make engineering decisions to drive forward.\nAnalytical Skills: Must be able to analyze complex systems and develop appropriate blueprints to make it understandable and useable.\nCommunication Skills: Must be an effective communicator.\nCollaboration Skills: Must be energetic, open and collaborative across all teams and roles.\nProblem-Solving Skills: Ability to focus on details while maintaining the “big picture” view.\nAgile Skills: Must have a strong understanding of Agile development principles and tools. Be passionate about failing fast and constantly iterating.\nDevelopment Skills: Must have a strong understanding of software architecture and design patterns.QUALIFICATIONS & EXPERIENCEBachelors/Master’s degree in Computer Science Engineering or a related field.\n5+ years of overall engineering (software development) experience.\nHands-on development, DevOps, and Agile delivery skills.\nContribution to the Open-Source community is desirable.\nHeavy exposure and implementation experience in modern technology, architecture, and automation patterns.NOTE:Only immediate joiners should apply#J-18808-Ljbffr",
		job_is_remote: false,
		job_posted_at_timestamp: 1704758400,
		job_posted_at_datetime_utc: "2024-01-09T00:00:00.000Z",
		job_city: "دبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 25.20485,
		job_longitude: 55.270782,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=rB-hrC0Y8rrN7X-qAAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-01-23T00:00:00.000Z",
		job_offer_expiration_timestamp: 1705968000,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 60,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: true,
			degree_preferred: true,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
	{
		employer_name: "CONNECTING 2 WORK",
		employer_logo:
			"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT_jV9Bz5DkbPPBfn9YPoSrDonzUPsa5al-mZn_&s=0",
		employer_website: null,
		employer_company_type: null,
		job_publisher: "Energy Jobline",
		job_id: "J0kIeewRHuk_2Mx9AAAAAA==",
		job_employment_type: "FULLTIME",
		job_title: "React js Developer",
		job_apply_link:
			"https://www.energyjobline.com/job/react-js-developer-13777730",
		job_apply_is_direct: false,
		job_apply_quality_score: 0.6412,
		apply_options: [
			{
				publisher: "Energy Jobline",
				apply_link:
					"https://www.energyjobline.com/job/react-js-developer-13777730",
				is_direct: false,
			},
			{
				publisher: "Expertini",
				apply_link:
					"https://ae.expertini.com/jobs/job/react-js-developer-abu-dhabi-connecting-2-work-67b4e2dd61/",
				is_direct: false,
			},
			{
				publisher: "Trabajo.org",
				apply_link:
					"https://ae.trabajo.org/job-721-20231226-1d3ca6c942eea0765bbf8a5493b045d6",
				is_direct: false,
			},
		],
		job_description:
			"Job Description Skills Required:– 3+ years of hands-on experience in ReactJS, React Redux, MobX, HTML5, CSS3, Typescript, JavaScript, Jest, mocha or other unit testing framework.– Experience Integrating with third-party libraries and APIs & Payment Gateways– Experience In-depth knowledge in JavaScript including ES6+ and Typescript– Deep understanding of Data Structures and ES6 Functionalities– Support, debug and provide enhancements to the existing applications– Translate frontend designs to Application screens– Use of proper design patterns to fit in the overall architecture and develop reusable components.",
		job_is_remote: false,
		job_posted_at_timestamp: 1702425600,
		job_posted_at_datetime_utc: "2023-12-13T00:00:00.000Z",
		job_city: "أبو ظبي",
		job_state: null,
		job_country: "AE",
		job_latitude: 24.453884,
		job_longitude: 54.377342,
		job_benefits: null,
		job_google_link:
			"https://www.google.com/search?gl=us&hl=en&rciv=jb&q=react+developer+in+uae&start=0&ibp=htl;jobs#fpstate=tldetail&htivrt=jobs&htiq=react+developer+in+uae&htidocid=J0kIeewRHuk_2Mx9AAAAAA%3D%3D",
		job_offer_expiration_datetime_utc: "2024-02-11T00:00:00.000Z",
		job_offer_expiration_timestamp: 1707609600,
		job_required_experience: {
			no_experience_required: false,
			required_experience_in_months: 36,
			experience_mentioned: true,
			experience_preferred: false,
		},
		job_required_skills: null,
		job_required_education: {
			postgraduate_degree: false,
			professional_certification: false,
			high_school: false,
			associates_degree: false,
			bachelors_degree: false,
			degree_mentioned: false,
			degree_preferred: false,
			professional_certification_mentioned: false,
		},
		job_experience_in_place_of_education: false,
		job_min_salary: null,
		job_max_salary: null,
		job_salary_currency: null,
		job_salary_period: null,
		job_highlights: {},
		job_job_title: null,
		job_posting_language: "en",
		job_onet_soc: "15113400",
		job_onet_job_zone: "3",
	},
];

export default dummyData;
